# Generated by Django 4.2.1 on 2023-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepientname', models.CharField(max_length=32)),
                ('recepientphone', models.CharField(max_length=32)),
                ('deliveryadress', models.CharField(max_length=32)),
                ('deliverydate', models.DateTimeField(auto_now_add=True)),
                ('deliverystatus', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], max_length=32)),
            ],
        ),
    ]
