# Generated by Django 4.2.3 on 2023-08-09 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_image'),
        ('delivery', '0002_alter_delivery_recepientname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='recepientname',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
