# Generated by Django 4.2.3 on 2023-08-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_delivery_recepientname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='recepientname',
            field=models.CharField(max_length=32),
        ),
    ]
