# Generated by Django 4.2.3 on 2023-08-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_delivery_recepientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='recepientname',
        ),
    ]
