# Generated by Django 4.2.3 on 2023-08-14 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_payment_nameofpayee_remove_payment_product_and_more'),
        ('delivery', '0009_alter_delivery_recepientname'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='payee',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
    ]
