# Generated by Django 4.2.3 on 2023-08-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_delivery_payee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='payee',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='recepientname',
        ),
    ]
