# Generated by Django 4.2.1 on 2023-06-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=32)),
                ('last_Name', models.CharField(max_length=32)),
                ('email_Address', models.EmailField(max_length=254)),
                ('phone_No', models.CharField(max_length=32)),
                ('account_password', models.CharField(max_length=32)),
                ('delivery_Location', models.CharField(max_length=32)),
            ],
        ),
    ]
