# Generated by Django 4.2.3 on 2023-08-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
