# Generated by Django 4.2.1 on 2023-06-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='nameofPayee',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentStatement',
            field=models.TextField(default=''),
        ),
    ]
