# Generated by Django 4.2.3 on 2023-08-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0005_alter_payment_nameofpayee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='nameofPayee',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
