# Generated by Django 4.2.3 on 2023-08-08 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0008_alter_payment_nameofpayee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='nameofPayee',
        ),
        migrations.AddField(
            model_name='payment',
            name='nameOfPayee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
