# Generated by Django 4.2.3 on 2023-08-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_product'),
        ('payment', '0010_payment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='nameOfPayee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
