# Generated by Django 4.2.3 on 2023-07-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_remove_order_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_method', models.CharField(choices=[('in-store pickup', 'in-store pickup'), ('home delivery', 'home delivery')], max_length=32)),
                ('delivery_date', models.DateTimeField()),
                ('delivery_status', models.CharField(choices=[('out for delivery', 'out for delivery'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], max_length=32)),
                ('signature_required', models.BooleanField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
