# Generated by Django 4.2.1 on 2023-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofProduct', models.CharField(max_length=32)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
                ('moderationStatus', models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=32)),
                ('flagged', models.BooleanField(default=False)),
                ('helpfulCount', models.PositiveIntegerField()),
            ],
        ),
    ]
