# Generated by Django 4.2.1 on 2023-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofproduct', models.CharField(max_length=32)),
                ('totalitems', models.PositiveIntegerField()),
                ('product_description', models.TextField()),
                ('priceofeach', models.DecimalField(decimal_places=2, max_digits=32)),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('cartstatus', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], max_length=32)),
            ],
        ),
    ]
