# Generated by Django 4.2.3 on 2023-07-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
        ('shoppingcart', '0002_shoppingcart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
