# Generated by Django 4.2.3 on 2023-07-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_shoppingcart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='product_description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='nameofproduct',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='priceofeach',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='totalamount',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='totalitems',
        ),
    ]
