# Generated by Django 4.2.3 on 2023-08-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_image'),
        ('shoppingcart', '0004_rename_product_description_shoppingcart_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='productS',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
