# Generated by Django 4.2.3 on 2023-08-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0006_rename_customer_shoppingcart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
