# Generated by Django 4.2.3 on 2023-09-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_image'),
        ('shoppingcart', '0007_remove_shoppingcart_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='images/')),
                ('date_added', models.DateTimeField()),
                ('products', models.ManyToManyField(to='inventory.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
