# Generated by Django 4.2.3 on 2023-07-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phoneNumber',
        ),
    ]
